/*
d/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientmanagementsystem;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import patientmanagementsystem.users.CreateUser;

/**
 *
 * @author jack-
 */
public class SecretaryPage extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryPage
     */
    public SecretaryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        loadrequestsButton = new javax.swing.JButton();
        denyButton = new javax.swing.JButton();
        patientapprovalLabel = new javax.swing.JLabel();
        approveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        useridtoapproveText = new javax.swing.JTextField();
        accountrequeststootltipLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        doctorSchedule = new javax.swing.JTable();
        patientapprovalLabel1 = new javax.swing.JLabel();
        approveappointmentButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        appointmentidInput = new javax.swing.JTextField();
        awaitingapprovalCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        loginnameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Secretary Page");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usersTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "Name", "Surname", "Gender", "DoB", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setEnabled(false);
        usersTable.setName("usersTable"); // NOI18N
        usersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(usersTable);
        if (usersTable.getColumnModel().getColumnCount() > 0) {
            usersTable.getColumnModel().getColumn(0).setHeaderValue("UserID");
            usersTable.getColumnModel().getColumn(1).setHeaderValue("Name");
            usersTable.getColumnModel().getColumn(2).setHeaderValue("Surname");
            usersTable.getColumnModel().getColumn(3).setHeaderValue("Gender");
            usersTable.getColumnModel().getColumn(4).setHeaderValue("DoB");
            usersTable.getColumnModel().getColumn(5).setHeaderValue("Address");
        }

        loadrequestsButton.setText("Load Table");
        loadrequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadrequestsButtonActionPerformed(evt);
            }
        });

        denyButton.setText("DENY");
        denyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denyButtonActionPerformed(evt);
            }
        });

        patientapprovalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientapprovalLabel.setText("User ID : ");

        approveButton.setText("APPROVE");
        approveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Patient Account Requests");

        useridtoapproveText.setToolTipText("Enter the UserID of the User you want to Approve/Deny");

        accountrequeststootltipLabel.setForeground(new java.awt.Color(204, 0, 0));
        accountrequeststootltipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loadrequestsButton)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(patientapprovalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountrequeststootltipLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(useridtoapproveText, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(approveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(denyButton)
                        .addGap(71, 71, 71)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadrequestsButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountrequeststootltipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientapprovalLabel)
                    .addComponent(useridtoapproveText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveButton)
                    .addComponent(denyButton))
                .addGap(52, 52, 52))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        doctorSchedule.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        doctorSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DoctorID", "PatientID", "Date"
            }
        ));
        doctorSchedule.setEnabled(false);
        doctorSchedule.setName("usersTable"); // NOI18N
        doctorSchedule.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(doctorSchedule);

        patientapprovalLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientapprovalLabel1.setText("Appointment ID (X-Number):");

        approveappointmentButton1.setText("APPROVE");
        approveappointmentButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveappointmentButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pending Appointment Requests");

        appointmentidInput.setToolTipText("Enter the UserID of the User you want to Approve/Deny");

        awaitingapprovalCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Click to load pending Appointments]" }));
        awaitingapprovalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awaitingapprovalComboActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Doctor Schedule");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(awaitingapprovalCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(patientapprovalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appointmentidInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(approveappointmentButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(awaitingapprovalCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientapprovalLabel1)
                    .addComponent(appointmentidInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(approveappointmentButton1)))
        );

        loginnameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginnameLabel.setText("<LOGIN NAME>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(loginnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(loginnameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login form = new Login();
        form.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadrequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadrequestsButtonActionPerformed
        // TODO add your handling code here:
        PopulateRequestsTable();
    }//GEN-LAST:event_loadrequestsButtonActionPerformed

    private void denyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denyButtonActionPerformed
        // Deny Button needs to search for the line that matches the input number and delete that line from the text file.
        
        // Approve Button needs to search for the string in PatientRequests.txt that matches the input ID. Then CreateUser with that data.
        String inputID = useridtoapproveText.getText();
        if(inputID.isEmpty()){
            accountrequeststootltipLabel.setText("Please enter a UserID");
            return;
        }
        String ID = "UNKNOWN";
        String name = "UNKNOWN";
        String surname = "UNKNOWN";
        String gender = "UNKNOWN";
        String dob = "UNKNOWN";
        String address = "UNKNOWN";
        String password = "UNKNOWN";
        
        //Search through PatientAccountsRequests.txt for this inputID and set all the relevant variables.
        BufferedReader br;
        String line;
        String[] userFields;
        Integer linenumber = 1;
        Integer resultlinenumber = 0;
        
        try{
            br = new BufferedReader(new FileReader("PatientAccountsRequests.txt"));
            while((line = br.readLine()) != null){
                userFields = line.split(",");
                if (userFields[0].equals(inputID)){
                    resultlinenumber = linenumber;
                    ID = userFields[0];
                    name = userFields[2];
                    surname = userFields[3];
                    gender = userFields[4];
                    dob = userFields[5];
                    address = userFields[6];
                    password = userFields[7];           
                }
                linenumber++;
            }

            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
         
        System.out.println("Deleting tempRecord.");
        
        String deleteText = ID + ",Patient," + name + "," + surname + "," + gender + "," + dob + "," + address + "," + password;
        
        File f = new File("PatientAccountsRequests.txt");
        try {
            //Delete the found record from the .txt file.
            br = new BufferedReader(new FileReader("PatientAccountsRequests.txt"));
            removeLine(f,deleteText);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
        PopulateRequestsTable();
        
    }//GEN-LAST:event_denyButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // Approve Button needs to search for the string in PatientRequests.txt that matches the input ID. Then CreateUser with that data.
        String inputID = useridtoapproveText.getText();
        if(inputID.isEmpty()){
            accountrequeststootltipLabel.setText("Please enter a UserID");
            return;
        }
        String ID = "UNKNOWN";
        String name = "UNKNOWN";
        String surname = "UNKNOWN";
        String gender = "UNKNOWN";
        String dob = "UNKNOWN";
        String address = "UNKNOWN";
        String password = "UNKNOWN";
        
        //Search through PatientAccountsRequests.txt for this inputID and set all the relevant variables.
        BufferedReader br;
        String line;
        String[] userFields;
        Integer linenumber = 1;
        Integer resultlinenumber = 0;
        
        try{
            br = new BufferedReader(new FileReader("PatientAccountsRequests.txt"));
            while((line = br.readLine()) != null){
                userFields = line.split(",");
                if (userFields[0].equals(inputID)){
                    resultlinenumber = linenumber;
                    ID = userFields[0];
                    name = userFields[2];
                    surname = userFields[3];
                    gender = userFields[4];
                    dob = userFields[5];
                    address = userFields[6];
                    password = userFields[7];           
                }
                linenumber++;
            }

            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
        
        System.out.println("Creating User Object.");
        //CreateUser with this data.
         CreateUser objCreateUser =
                new CreateUser("Patient",name,surname,gender,dob,address,password);
         
        System.out.println("Deleting tempRecord.");
        
        String deleteText = ID + ",Patient," + name + "," + surname + "," + gender + "," + dob + "," + address + "," + password;
        
        File f = new File("PatientAccountsRequests.txt");
        try {
            //Delete the found record from the .txt file.
            br = new BufferedReader(new FileReader("PatientAccountsRequests.txt"));
            removeLine(f,deleteText);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
        PopulateRequestsTable();
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_approveButtonActionPerformed

    private void approveappointmentButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveappointmentButton1ActionPerformed
        // TODO add your handling code here:
        String SearchID = appointmentidInput.getText();
        Boolean foundRecord = false;
        BufferedReader br;
        String line;
        String[] appointmentFields;
        Integer linenumber = 1;    
        try{
            br = new BufferedReader(new FileReader("Appointments.txt"));
            while((line = br.readLine()) != null){
                appointmentFields = line.split(",");
                if (appointmentFields[0].equals(SearchID)){
                    
                    String newline = appointmentFields[0] + ",Approved," + appointmentFields[2] + "," + appointmentFields[3] + "," + appointmentFields[4]  + "," + appointmentFields[5]; 
                    
                    List<String> fileContent;
                        fileContent = new ArrayList<>(Files.readAllLines(Paths.get("Appointments.txt")));
                        for (int i = 0; i < fileContent.size(); i++) {
                            if (fileContent.get(i).equals(line)) {
                                fileContent.set(i, newline);
                            break;
                            }
                        }
                Files.write(Paths.get("Appointments.txt"), fileContent);
                foundRecord = true;
                }
                linenumber++;
            }

            br.close();
            }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
            }
        if(foundRecord == false){
            JOptionPane.showMessageDialog(null, "Invalid ID Input","ERROR",JOptionPane.OK_CANCEL_OPTION);
            
        }
        else if(foundRecord == true)
        {
            JOptionPane.showMessageDialog(null, "Appointment Approved","Success",JOptionPane.OK_CANCEL_OPTION);
            appointmentidInput.getText();
            PopulateAppointmentRequests();
        }
    }//GEN-LAST:event_approveappointmentButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        loginnameLabel.setText(Login.LoginName);
    }//GEN-LAST:event_formWindowActivated

    private void awaitingapprovalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awaitingapprovalComboActionPerformed
        // TODO add your handling code here:
        
        if(awaitingapprovalCombo.getSelectedItem().toString() == "[Click to load pending Appointments]"){
            PopulateAppointmentRequests();
        }else{
            String[] SelectedItem = awaitingapprovalCombo.getSelectedItem().toString().split("-");
            System.out.println(SelectedItem[1] + " " + SelectedItem[3]);
            PopulateDoctorSchedule(SelectedItem[1],SelectedItem[3]);
        }
            
        
    }//GEN-LAST:event_awaitingapprovalComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryPage().setVisible(true);
            }
        });
    }
    public void PopulateRequestsTable(){
        BufferedReader br;
        DefaultTableModel model = (DefaultTableModel) usersTable.getModel();
        
        model.setRowCount(0);
        String line;
        Integer linenumber = 1;
        
        usersTable.getTableHeader().setReorderingAllowed(false);
        
        
        try{
            br = new BufferedReader(new FileReader("PatientAccountsRequests.txt"));       
            while((line = br.readLine()) != null){
                String[] userFields = line.split(",");
                model.addRow(new Object[]{userFields[0],userFields[2],userFields[3],userFields[4],userFields[5],userFields[6]});
                linenumber++;
            }

            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
    }   
    public void AddLine(String path,String text) throws IOException{
        //Saves the text that's passed in to the Text File.
        FileWriter write = new FileWriter(path, true);
        PrintWriter print_line = new PrintWriter(write);
        
        print_line.printf("%s" + "%n", text);
        
        print_line.close();
      
    }
    public static void removeLine(File f, String Line) throws IOException{
        
        BufferedReader br = new BufferedReader(new FileReader(f));
        File temp = new File("temp.txt");
        BufferedWriter bw = new BufferedWriter(new FileWriter(temp));
        String removeID = Line;
        String currentLine;
        while((currentLine = br.readLine()) != null){
            String trimmedLine = currentLine.trim();
            if(trimmedLine.equals(removeID)){
                currentLine = null;
            }
        }
        bw.close();
        br.close();
        boolean delete = f.delete();
        boolean b = temp.renameTo(f);
        
    }
    public String RetrieveUsersName(String UserID){
        
        String UsersName = "";
        BufferedReader br;
        String line;
        String[] userFields;
        Integer linenumber = 1;
        
        try{
            br = new BufferedReader(new FileReader("Users.txt"));
            while((line = br.readLine()) != null){
                userFields = line.split(",");
                if (userFields[0].equals(UserID)){
                    UsersName = userFields[2] + " " + userFields[3];
                }
                linenumber++;
            }

            br.close();
        }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
        }
        
        return UsersName;
    }
    public void PopulateDoctorSchedule(String DoctorID,String Date){
        
        DefaultTableModel model = (DefaultTableModel) doctorSchedule.getModel();
        model.setRowCount(0);
        BufferedReader br;
        String line;
        String[] appointmentFields;
        Integer linenumber = 1;
        try{
                br = new BufferedReader(new FileReader("Appointments.txt"));
                while((line = br.readLine()) != null){
                appointmentFields = line.split(",");
                if (appointmentFields[1].equals("Approved")){
                   if(appointmentFields[2].equals(DoctorID)){
                       if(appointmentFields[4].equals(Date)){
                           System.out.println("Matched Appointment");
                           model.addRow(new Object[]{appointmentFields[2],appointmentFields[3],appointmentFields[4]});
                       }
                   }
                }
                linenumber++;
            }

            br.close();
            }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
            }
        
    }
    public void PopulateAppointmentRequests(){
            BufferedReader br;
            String line;
            String[] appointmentFields;
            Integer linenumber = 1;
            awaitingapprovalCombo.removeAllItems();
            try{
                br = new BufferedReader(new FileReader("Appointments.txt"));
                while((line = br.readLine()) != null){
                appointmentFields = line.split(",");
                if (appointmentFields[1].equals("Awaiting")){
                    String string = (appointmentFields[4]);
                    DateFormat format;
                    format = new SimpleDateFormat("EEE MMM d HH:mm:ss z yyyy");
                    Date appointmentDate = format.parse(string); 
                    awaitingapprovalCombo.addItem(appointmentFields[0] + ":" + RetrieveUsersName(appointmentFields[3]) + " for " + RetrieveUsersName(appointmentFields[2]) + " -" + appointmentFields[2]+"- " + " on -" + appointmentDate);       
                }
                linenumber++;
            }

            br.close();
            }catch(IOException e){
            JOptionPane.showMessageDialog(null, e,"ERROR",JOptionPane.OK_CANCEL_OPTION);
            } catch (ParseException ex) {
            Logger.getLogger(SecretaryPage.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountrequeststootltipLabel;
    private javax.swing.JTextField appointmentidInput;
    private javax.swing.JButton approveButton;
    private javax.swing.JButton approveappointmentButton1;
    private javax.swing.JComboBox<String> awaitingapprovalCombo;
    private javax.swing.JButton denyButton;
    private javax.swing.JTable doctorSchedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadrequestsButton;
    private javax.swing.JLabel loginnameLabel;
    private javax.swing.JLabel patientapprovalLabel;
    private javax.swing.JLabel patientapprovalLabel1;
    private javax.swing.JTextField useridtoapproveText;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
